import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service - BustedLab",
  description: "BustedLab terms of service and legal disclaimers.",
};

export default function TermsPage() {
  return (
    <main style={{ maxWidth: "720px", margin: "0 auto", padding: "48px 24px 80px", color: "var(--text)", fontFamily: "var(--font-sans), sans-serif" }}>
      <Link href="/" style={{ color: "var(--accent-bright)", textDecoration: "none", fontSize: "14px", display: "inline-flex", alignItems: "center", gap: "6px", marginBottom: "32px" }}>
        ← Back to BustedLab
      </Link>

      <h1 style={{ fontFamily: "var(--font-display), sans-serif", fontSize: "32px", fontWeight: "700", letterSpacing: "-0.8px", marginBottom: "8px" }}>Terms of Service</h1>
      <p style={{ color: "var(--text-3)", fontSize: "13px", marginBottom: "40px" }}>Terms version 3.0 · BustedLab LLC, Wyoming, USA</p>

      <div style={{ display: "flex", flexDirection: "column", gap: "32px", fontSize: "15px", lineHeight: "1.75", color: "var(--text-2)" }}>

        <section>
          <h2 style={{ fontFamily: "var(--font-display), sans-serif", fontSize: "18px", fontWeight: "700", color: "var(--text)", marginBottom: "12px" }}>1. Nature of the Service</h2>
          <p>BustedLab is a consumer intelligence platform that provides market analysis of wholesale pricing for product categories. All results, verdicts, markups, and price references generated by BustedLab are <strong style={{ color: "var(--text)" }}>market analysis and editorial opinion</strong> based on publicly available wholesale listings for similar or comparable products, not verified statements of fact about any specific named product or brand.</p>
          <p style={{ marginTop: "12px" }}>BustedLab operates in the tradition of consumer advocacy journalism and price comparison services, activities that are explicitly protected under the First Amendment of the United States Constitution and equivalent protections in other jurisdictions. Our analysis is provided for informational, educational, and consumer empowerment purposes only.</p>
        </section>

        <section>
          <h2 style={{ fontFamily: "var(--font-display), sans-serif", fontSize: "18px", fontWeight: "700", color: "var(--text)", marginBottom: "12px" }}>2. Accuracy Disclaimer</h2>
          <p>All pricing data, markup percentages, and wholesale cost estimates reflect publicly available market data for <em>similar or comparable products</em> at the time of analysis. BustedLab does not guarantee that scan results reflect the exact manufacturing cost, wholesale price, or retail price of any specific product.</p>
          <p style={{ marginTop: "12px" }}>Prices vary by supplier, region, order quantity, time, and product specification. Results should be used as general market intelligence only. BustedLab makes no warranties, express or implied, regarding the accuracy, completeness, or fitness for any particular purpose of any scan result.</p>
          <p style={{ marginTop: "12px" }}>The Service is provided on an &ldquo;AS IS&rdquo; and &ldquo;AS AVAILABLE&rdquo; basis. To the maximum extent permitted by law, BustedLab LLC disclaims all warranties of any kind.</p>
        </section>

        <section>
          <h2 style={{ fontFamily: "var(--font-display), sans-serif", fontSize: "18px", fontWeight: "700", color: "var(--text)", marginBottom: "12px" }}>2a. Unlimited access and fair use</h2>
          <p>Paid access includes unlimited scans for personal and business use. &ldquo;Unlimited&rdquo; is not qualified by a quota you are likely to meet: there is a fair-use ceiling of 500 scans per account per 24 hours, which exists to stop automated or shared use of a single account and which no ordinary use approaches. It resets at 00:00 UTC. If you have a legitimate need above it, email <a href="mailto:support@bustedlab.com" style={{ color: "var(--accent-bright)" }}>support@bustedlab.com</a> and we will raise it for your account.</p>
          <p style={{ marginTop: "12px" }}>We state the number rather than reserving a vague right to throttle, because a limit you cannot see is not a term you agreed to.</p>

          <h2 style={{ fontFamily: "var(--font-display), sans-serif", fontSize: "18px", fontWeight: "700", color: "var(--text)", marginBottom: "12px", marginTop: "28px" }}>3. Limitation of Liability</h2>
          <p>BustedLab LLC shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from your use of the Service or reliance on any scan result. In no event shall our total liability to you exceed the amount you paid for the Service in the twelve months preceding the claim.</p>
          <p style={{ marginTop: "12px" }}>You agree that BustedLab scan results do not constitute financial, legal, or purchasing advice. You are solely responsible for any decisions made based on information provided by the Service.</p>
        </section>

        <section>
          <h2 style={{ fontFamily: "var(--font-display), sans-serif", fontSize: "18px", fontWeight: "700", color: "var(--text)", marginBottom: "12px" }}>4. User Conduct</h2>
          <p>You agree not to use the Service to harass, defame, or make false statements about any individual or business. You agree to use scan results only as general market intelligence and not to present BustedLab analysis as verified factual claims about specific products or businesses.</p>
          <p style={{ marginTop: "12px" }}>You are responsible for how you share or use scan results. BustedLab is not liable for how users choose to share or present information derived from the Service.</p>
        </section>

        <section>
          <h2 style={{ fontFamily: "var(--font-display), sans-serif", fontSize: "18px", fontWeight: "700", color: "var(--text)", marginBottom: "12px" }}>5. Intellectual Property</h2>
          <p>The BustedLab name, logo, interface design, and underlying technology are the intellectual property of BustedLab LLC. You may share Verdict Cards generated by the Service for personal, non-commercial, and consumer advocacy purposes with attribution to BustedLab.</p>
          <p style={{ marginTop: "12px" }}>Product images shown in scan results are retrieved from publicly available merchant listings and displayed for the purpose of price comparison and commentary. BustedLab claims no ownership of them. Rights holders may contact us through the DMCA process.</p>
        </section>

        <section>
          <h2 style={{ fontFamily: "var(--font-display), sans-serif", fontSize: "18px", fontWeight: "700", color: "var(--text)", marginBottom: "12px" }}>6. Affiliate Relationships</h2>
          <p>BustedLab participates in affiliate marketing programs. When you click links to wholesale or retail sources in scan results and make a purchase, BustedLab may receive a commission. This does not affect the price you pay. All affiliate relationships are disclosed on results pages in compliance with FTC guidelines and equivalent international regulations.</p>
        </section>

        <section>
          <h2 style={{ fontFamily: "var(--font-display), sans-serif", fontSize: "18px", fontWeight: "700", color: "var(--text)", marginBottom: "12px" }}>7. Payments and Refunds</h2>
          <p>BustedLab offers a one-time lifetime access purchase. Payment is processed by a third-party provider acting as Merchant of Record, named on the checkout page before you enter any details. Given the immediate and complete delivery of digital service access upon payment, refunds are offered only where required by applicable consumer protection law in your jurisdiction, including the statutory withdrawal rights of consumers in the EU and UK. Where a full refund or a chargeback is processed, access to the Service is withdrawn. A partial refund does not affect access.</p>
        </section>

        <section>
          <h2 style={{ fontFamily: "var(--font-display), sans-serif", fontSize: "18px", fontWeight: "700", color: "var(--text)", marginBottom: "12px" }}>8. Governing Law</h2>
          <p>These Terms are governed by the laws of the State of Wyoming, United States, without regard to conflict of law principles. Any disputes shall be resolved exclusively in Wyoming state courts or the federal courts of Wyoming.</p>
        </section>

        <section>
          <h2 style={{ fontFamily: "var(--font-display), sans-serif", fontSize: "18px", fontWeight: "700", color: "var(--text)", marginBottom: "12px" }}>9. Changes to Terms</h2>
          <p>We reserve the right to update these Terms at any time. Continued use of the Service following any update constitutes your acceptance of the revised Terms.</p>
        </section>

        <section>
          <h2 style={{ fontFamily: "var(--font-display), sans-serif", fontSize: "18px", fontWeight: "700", color: "var(--text)", marginBottom: "12px" }}>10. Contact</h2>
          <p>Legal inquiries: <a href="mailto:legal@bustedlab.com" style={{ color: "var(--accent-bright)" }}>legal@bustedlab.com</a><br />BustedLab LLC · Wyoming, USA</p>
        </section>
      </div>
    </main>
  );
}
