import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service - BustedLab",
  description: "BustedLab terms of service and legal disclaimers.",
};

export default function TermsPage() {
  return (
    <main style={{ maxWidth: "720px", margin: "0 auto", padding: "48px 24px 80px", color: "var(--text)", fontFamily: "'Inter', sans-serif" }}>
      <a href="/" style={{ color: "var(--accent-bright)", textDecoration: "none", fontSize: "14px", display: "inline-flex", alignItems: "center", gap: "6px", marginBottom: "32px" }}>
        ← Back to BustedLab
      </a>

      <h1 style={{ fontFamily: "'Space Grotesk', sans-serif", fontSize: "32px", fontWeight: "700", letterSpacing: "-0.8px", marginBottom: "8px" }}>Terms of Service</h1>
      <p style={{ color: "var(--text-3)", fontSize: "13px", marginBottom: "40px" }}>Last updated: September 2026 · BustedLab LLC, Wyoming, USA</p>

      <div style={{ display: "flex", flexDirection: "column", gap: "32px", fontSize: "15px", lineHeight: "1.75", color: "var(--text-2)" }}>

        <section>
          <h2 style={{ fontFamily: "'Space Grotesk', sans-serif", fontSize: "18px", fontWeight: "700", color: "var(--text)", marginBottom: "12px" }}>1. Nature of the Service</h2>
          <p>BustedLab is a consumer intelligence platform that provides market analysis of wholesale pricing for product categories. All results, verdicts, markups, and price references generated by BustedLab are <strong style={{ color: "var(--text)" }}>market analysis and editorial opinion</strong> based on publicly available wholesale listings for similar or comparable products - not verified statements of fact about any specific named product or brand.</p>
          <p style={{ marginTop: "12px" }}>BustedLab operates in the tradition of consumer advocacy journalism and price comparison services, activities that are explicitly protected under the First Amendment of the United States Constitution and equivalent protections in other jurisdictions. Our analysis is provided for informational, educational, and consumer empowerment purposes only.</p>
        </section>

        <section>
          <h2 style={{ fontFamily: "'Space Grotesk', sans-serif", fontSize: "18px", fontWeight: "700", color: "var(--text)", marginBottom: "12px" }}>2. Accuracy Disclaimer</h2>
          <p>All pricing data, markup percentages, and wholesale cost estimates reflect publicly available market data for <em>similar or comparable products</em> at the time of analysis. BustedLab does not guarantee that scan results reflect the exact manufacturing cost, wholesale price, or retail price of any specific product.</p>
          <p style={{ marginTop: "12px" }}>Prices vary by supplier, region, order quantity, time, and product specification. Results should be used as general market intelligence only. BustedLab makes no warranties, express or implied, regarding the accuracy, completeness, or fitness for any particular purpose of any scan result.</p>
          <p style={{ marginTop: "12px" }}>The Service is provided on an "AS IS" and "AS AVAILABLE" basis. To the maximum extent permitted by law, BustedLab LLC disclaims all warranties of any kind.</p>
        </section>

        <section>
          <h2 style={{ fontFamily: "'Space Grotesk', sans-serif", fontSize: "18px", fontWeight: "700", color: "var(--text)", marginBottom: "12px" }}>3. Limitation of Liability</h2>
          <p>BustedLab LLC shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from your use of the Service or reliance on any scan result. In no event shall our total liability to you exceed the amount you paid for the Service in the twelve months preceding the claim.</p>
          <p style={{ marginTop: "12px" }}>You agree that BustedLab scan results do not constitute financial, legal, or purchasing advice. You are solely responsible for any decisions made based on information provided by the Service.</p>
        </section>

        <section>
          <h2 style={{ fontFamily: "'Space Grotesk', sans-serif", fontSize: "18px", fontWeight: "700", color: "var(--text)", marginBottom: "12px" }}>4. User Conduct</h2>
          <p>You agree not to use the Service to harass, defame, or make false statements about any individual or business. You agree to use scan results only as general market intelligence and not to present BustedLab analysis as verified factual claims about specific products or businesses.</p>
          <p style={{ marginTop: "12px" }}>You are responsible for how you share or use scan results. BustedLab is not liable for how users choose to share or present information derived from the Service.</p>
        </section>

        <section>
          <h2 style={{ fontFamily: "'Space Grotesk', sans-serif", fontSize: "18px", fontWeight: "700", color: "var(--text)", marginBottom: "12px" }}>5. Intellectual Property</h2>
          <p>The BustedLab name, logo, interface design, and underlying technology are the intellectual property of BustedLab LLC. You may share Verdict Cards generated by the Service for personal, non-commercial, and consumer advocacy purposes with attribution to BustedLab.</p>
        </section>

        <section>
          <h2 style={{ fontFamily: "'Space Grotesk', sans-serif", fontSize: "18px", fontWeight: "700", color: "var(--text)", marginBottom: "12px" }}>6. Affiliate Relationships</h2>
          <p>BustedLab participates in affiliate marketing programs. When you click links to wholesale or retail sources in scan results and make a purchase, BustedLab may receive a commission. This does not affect the price you pay. All affiliate relationships are disclosed on results pages in compliance with FTC guidelines and equivalent international regulations.</p>
        </section>

        <section>
          <h2 style={{ fontFamily: "'Space Grotesk', sans-serif", fontSize: "18px", fontWeight: "700", color: "var(--text)", marginBottom: "12px" }}>7. Payments and Refunds</h2>
          <p>BustedLab offers a one-time lifetime access purchase processed by Lemon Squeezy, our payment provider and Merchant of Record. All payments are final. Given the immediate and complete delivery of digital service access upon payment, we do not offer refunds except where required by applicable consumer protection law in your jurisdiction.</p>
        </section>

        <section>
          <h2 style={{ fontFamily: "'Space Grotesk', sans-serif", fontSize: "18px", fontWeight: "700", color: "var(--text)", marginBottom: "12px" }}>8. Governing Law</h2>
          <p>These Terms are governed by the laws of the State of Wyoming, United States, without regard to conflict of law principles. Any disputes shall be resolved exclusively in Wyoming state courts or the federal courts of Wyoming.</p>
        </section>

        <section>
          <h2 style={{ fontFamily: "'Space Grotesk', sans-serif", fontSize: "18px", fontWeight: "700", color: "var(--text)", marginBottom: "12px" }}>9. Changes to Terms</h2>
          <p>We reserve the right to update these Terms at any time. Continued use of the Service following any update constitutes your acceptance of the revised Terms.</p>
        </section>

        <section>
          <h2 style={{ fontFamily: "'Space Grotesk', sans-serif", fontSize: "18px", fontWeight: "700", color: "var(--text)", marginBottom: "12px" }}>10. Contact</h2>
          <p>Legal inquiries: <a href="mailto:legal@bustedlab.com" style={{ color: "var(--accent-bright)" }}>legal@bustedlab.com</a><br />BustedLab LLC · Wyoming, USA</p>
        </section>
      </div>
    </main>
  );
}
